/* Auto-generated by genmsg_cpp for file /rahome/ait_jellal/projects/src/libks/msg/MultiCameraImage.msg */
#ifndef LIBKS_MESSAGE_MULTICAMERAIMAGE_H
#define LIBKS_MESSAGE_MULTICAMERAIMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"

namespace libks
{
template <class ContainerAllocator>
struct MultiCameraImage_ {
  typedef MultiCameraImage_<ContainerAllocator> Type;

  MultiCameraImage_()
  : header()
  , cam0()
  , cam1()
  , cam2()
  , cam3()
  {
  }

  MultiCameraImage_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , cam0(_alloc)
  , cam1(_alloc)
  , cam2(_alloc)
  , cam3(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam0_type;
   ::sensor_msgs::Image_<ContainerAllocator>  cam0;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam1_type;
   ::sensor_msgs::Image_<ContainerAllocator>  cam1;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam2_type;
   ::sensor_msgs::Image_<ContainerAllocator>  cam2;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam3_type;
   ::sensor_msgs::Image_<ContainerAllocator>  cam3;


  typedef boost::shared_ptr< ::libks::MultiCameraImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::libks::MultiCameraImage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MultiCameraImage
typedef  ::libks::MultiCameraImage_<std::allocator<void> > MultiCameraImage;

typedef boost::shared_ptr< ::libks::MultiCameraImage> MultiCameraImagePtr;
typedef boost::shared_ptr< ::libks::MultiCameraImage const> MultiCameraImageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::libks::MultiCameraImage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::libks::MultiCameraImage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace libks

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::libks::MultiCameraImage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::libks::MultiCameraImage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::libks::MultiCameraImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8b44608bfb0d2204398483be4d01ac1f";
  }

  static const char* value(const  ::libks::MultiCameraImage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8b44608bfb0d2204ULL;
  static const uint64_t static_value2 = 0x398483be4d01ac1fULL;
};

template<class ContainerAllocator>
struct DataType< ::libks::MultiCameraImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "libks/MultiCameraImage";
  }

  static const char* value(const  ::libks::MultiCameraImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::libks::MultiCameraImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Old message type! Only used for backward compatibility!\n\
\n\
# Up to 4 cameras are supported but not all cameras\n\
# need to be activated.\n\
\n\
Header header\n\
\n\
sensor_msgs/Image cam0\n\
sensor_msgs/Image cam1\n\
sensor_msgs/Image cam2\n\
sensor_msgs/Image cam3\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
";
  }

  static const char* value(const  ::libks::MultiCameraImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::libks::MultiCameraImage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::libks::MultiCameraImage_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::libks::MultiCameraImage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.cam0);
    stream.next(m.cam1);
    stream.next(m.cam2);
    stream.next(m.cam3);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MultiCameraImage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::libks::MultiCameraImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::libks::MultiCameraImage_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cam0: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam0);
    s << indent << "cam1: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam1);
    s << indent << "cam2: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam2);
    s << indent << "cam3: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam3);
  }
};


} // namespace message_operations
} // namespace ros

#endif // LIBKS_MESSAGE_MULTICAMERAIMAGE_H

