/* Auto-generated by genmsg_cpp for file /rahome/ait_jellal/projects/src/libks/msg/SharedImageSet.msg */
#ifndef LIBKS_MESSAGE_SHAREDIMAGESET_H
#define LIBKS_MESSAGE_SHAREDIMAGESET_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace libks
{
template <class ContainerAllocator>
struct SharedImageSet_ {
  typedef SharedImageSet_<ContainerAllocator> Type;

  SharedImageSet_()
  : header()
  , imagePtrs()
  {
  }

  SharedImageSet_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , imagePtrs(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _imagePtrs_type;
  std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  imagePtrs;


  typedef boost::shared_ptr< ::libks::SharedImageSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::libks::SharedImageSet_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SharedImageSet
typedef  ::libks::SharedImageSet_<std::allocator<void> > SharedImageSet;

typedef boost::shared_ptr< ::libks::SharedImageSet> SharedImageSetPtr;
typedef boost::shared_ptr< ::libks::SharedImageSet const> SharedImageSetConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::libks::SharedImageSet_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::libks::SharedImageSet_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace libks

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::libks::SharedImageSet_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::libks::SharedImageSet_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::libks::SharedImageSet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0d17d1086d8c500eecddadc40f6db542";
  }

  static const char* value(const  ::libks::SharedImageSet_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0d17d1086d8c500eULL;
  static const uint64_t static_value2 = 0xecddadc40f6db542ULL;
};

template<class ContainerAllocator>
struct DataType< ::libks::SharedImageSet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "libks/SharedImageSet";
  }

  static const char* value(const  ::libks::SharedImageSet_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::libks::SharedImageSet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
uint64[] imagePtrs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::libks::SharedImageSet_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::libks::SharedImageSet_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::libks::SharedImageSet_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::libks::SharedImageSet_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.imagePtrs);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SharedImageSet_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::libks::SharedImageSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::libks::SharedImageSet_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "imagePtrs[]" << std::endl;
    for (size_t i = 0; i < v.imagePtrs.size(); ++i)
    {
      s << indent << "  imagePtrs[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.imagePtrs[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // LIBKS_MESSAGE_SHAREDIMAGESET_H

