#include <vector>
#include <opencv2/opencv.hpp>

extern void make_offsets(int pixel[], int row_stride);

// The autogenerated functions
extern void faster_detect(const cv::Mat_<unsigned char>& i, std::vector<cv::Point2i>& corners, int b);
extern void faster_score(const cv::Mat_<unsigned char>& i, const std::vector<cv::Point2i>& corners, int b,
	std::vector<int>& scores);

// OpenCV-like interface
extern void FASTER(const cv::Mat_<unsigned char>& image, std::vector<cv::KeyPoint>& keypoints, int threshold,
	bool nonmax_suppression = true);
