// Generated by gencpp from file libks_msgs/MultiCameraImage.msg
// DO NOT EDIT!


#ifndef LIBKS_MSGS_MESSAGE_MULTICAMERAIMAGE_H
#define LIBKS_MSGS_MESSAGE_MULTICAMERAIMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace libks_msgs
{
template <class ContainerAllocator>
struct MultiCameraImage_
{
  typedef MultiCameraImage_<ContainerAllocator> Type;

  MultiCameraImage_()
    : header()
    , cam0()
    , cam1()
    , cam2()
    , cam3()  {
    }
  MultiCameraImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cam0(_alloc)
    , cam1(_alloc)
    , cam2(_alloc)
    , cam3(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam0_type;
  _cam0_type cam0;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam1_type;
  _cam1_type cam1;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam2_type;
  _cam2_type cam2;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _cam3_type;
  _cam3_type cam3;




  typedef boost::shared_ptr< ::libks_msgs::MultiCameraImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::libks_msgs::MultiCameraImage_<ContainerAllocator> const> ConstPtr;

}; // struct MultiCameraImage_

typedef ::libks_msgs::MultiCameraImage_<std::allocator<void> > MultiCameraImage;

typedef boost::shared_ptr< ::libks_msgs::MultiCameraImage > MultiCameraImagePtr;
typedef boost::shared_ptr< ::libks_msgs::MultiCameraImage const> MultiCameraImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::libks_msgs::MultiCameraImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace libks_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'libks_msgs': ['/home/sun/catkin_ws/src/libks_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::libks_msgs::MultiCameraImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::libks_msgs::MultiCameraImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::libks_msgs::MultiCameraImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b44608bfb0d2204398483be4d01ac1f";
  }

  static const char* value(const ::libks_msgs::MultiCameraImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b44608bfb0d2204ULL;
  static const uint64_t static_value2 = 0x398483be4d01ac1fULL;
};

template<class ContainerAllocator>
struct DataType< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "libks_msgs/MultiCameraImage";
  }

  static const char* value(const ::libks_msgs::MultiCameraImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Old message type! Only used for backward compatibility!\n\
\n\
# Up to 4 cameras are supported but not all cameras\n\
# need to be activated.\n\
\n\
Header header\n\
\n\
sensor_msgs/Image cam0\n\
sensor_msgs/Image cam1\n\
sensor_msgs/Image cam2\n\
sensor_msgs/Image cam3\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
";
  }

  static const char* value(const ::libks_msgs::MultiCameraImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cam0);
      stream.next(m.cam1);
      stream.next(m.cam2);
      stream.next(m.cam3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiCameraImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::libks_msgs::MultiCameraImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::libks_msgs::MultiCameraImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cam0: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam0);
    s << indent << "cam1: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam1);
    s << indent << "cam2: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam2);
    s << indent << "cam3: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.cam3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIBKS_MSGS_MESSAGE_MULTICAMERAIMAGE_H
