set(_CATKIN_CURRENT_PACKAGE "libks")
set(libks_VERSION "0.0.1")
set(libks_MAINTAINER "Konstanin Schauwecker <konstantin.schauwecker@uni-tuebingen.de>")
set(libks_PACKAGE_FORMAT "1")
set(libks_BUILD_DEPENDS "roscpp" "rospy" "cmake_modules" "cv_bridge" "libelas" "libks_msgs" "opencv2" "rosconsole" "roscpp" "sensor_msgs" "tf")
set(libks_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "cmake_modules" "cv_bridge" "libelas" "libks_msgs" "opencv2" "rosconsole" "roscpp" "sensor_msgs" "tf")
set(libks_BUILDTOOL_DEPENDS "catkin")
set(libks_BUILDTOOL_EXPORT_DEPENDS )
set(libks_EXEC_DEPENDS "roscpp" "rospy" "cmake_modules" "cv_bridge" "libelas" "libks_msgs" "opencv2" "rosconsole" "roscpp" "sensor_msgs" "tf")
set(libks_RUN_DEPENDS "roscpp" "rospy" "cmake_modules" "cv_bridge" "libelas" "libks_msgs" "opencv2" "rosconsole" "sensor_msgs" "tf")
set(libks_TEST_DEPENDS )
set(libks_DOC_DEPENDS )
set(libks_DEPRECATED "")