set(_CATKIN_CURRENT_PACKAGE "capture")
set(capture_VERSION "0.0.1")
set(capture_MAINTAINER "Radouane Ait Jellal <radouane.ait-jellal@uni-tuebingen.de>")
set(capture_PACKAGE_FORMAT "1")
set(capture_BUILD_DEPENDS "sensor_msgs" "roscpp" "libks" "libks_msgs" "nodelet" "opencv2")
set(capture_BUILD_EXPORT_DEPENDS "sensor_msgs" "roscpp" "nodelet" "libks" "libks_msgs" "opencv2")
set(capture_BUILDTOOL_DEPENDS "catkin")
set(capture_BUILDTOOL_EXPORT_DEPENDS )
set(capture_EXEC_DEPENDS "sensor_msgs" "roscpp" "nodelet" "libks" "libks_msgs" "opencv2")
set(capture_RUN_DEPENDS "sensor_msgs" "roscpp" "nodelet" "libks" "libks_msgs" "opencv2")
set(capture_TEST_DEPENDS )
set(capture_DOC_DEPENDS )
set(capture_DEPRECATED "")